version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "michigang1"
      MYSQL_PASSWORD: "michigang1"
      MYSQL_HOST: "db"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mysql_network
  db:
    container_name: mysql
    image: mysql:8.1
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "michigang1"
      MYSQL_PASSWORD: "michigang1"
      MYSQL_HOST: "db"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      - mysql_network
volumes:
  mysql_volume:

networks:
  mysql_network: